# - name: Stop Docker service
#   ansible.builtin.service:
#     name: docker
#     state: stopped

# - name: Delete docker is already there
#   ansible.builtin.shell: |
#     for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
#       sudo apt-get remove -y $pkg
#     done

# - name: Remove Docker engine and related packages
#   ansible.builtin.apt:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#       - docker-buildx-plugin
#       - docker-compose-plugin
#     state: absent
#     purge: true

# - name: Autoremove unnecessary packages
#   ansible.builtin.apt:
#     autoremove: true
#     purge: true

# - name: Autoclean package cache
#   ansible.builtin.apt:
#     autoclean: true

# - name: Remove Docker binaries from multiple locations
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - /var/lib/docker
#     - /var/lib/docker-containerd
