plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-2
hostnames:
  - instance-id
filters:
  tag:Name: [WebsiteServer, ApiServer]
keyed_groups:
  - key: tags['Name']
    prefix: ''
    parent_group: "Project"

