name: Deploy and configure infra
run-name: Setting up infra
on: [push]
#   push:
#     branches:
#       - "main"

jobs:
  #   Build-infra:
  #     runs-on: ubuntu-latest

  #     steps:
  #       - name: Check out this repository
  #         uses: actions/checkout@v3

  #       - uses: hashicorp/setup-terraform@v3
  #         with:
  #           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  #       - name: Terraform format
  #         working-directory: ./Terraform
  #         run: terraform fmt -check
  #         continue-on-error: true

  #       - name: Terraform initialise
  #         working-directory: ./Terraform
  #         run: terraform init

  #       - name: Terraform validate
  #         working-directory: ./Terraform
  #         run: terraform validate

  #       - name: Terraform plan
  #         working-directory: ./Terraform
  #         run: terraform plan
  #         continue-on-error: false

  #       - name: Terraform apply
  #         working-directory: ./Terraform
  #         run: terraform apply -auto-approve
  #         continue-on-error: false

  Configure-infra:
    # needs: Build-infra
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          pip install boto3
          pip install botocore

      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Configure frontend server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ github.workspace }}/Ansible/Playbooks/frontend.yml
          directory: ${{ github.workspace }}/Ansible
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          #   inventory: ${{ github.workspace }}/Ansible/aws_ec2.yml
          requirements: ${{ github.workspace }}/Ansible/requirements.yml
          options: |
            --inventory aws_ec2.yml
            --verbose

    #   - name: Configure backend server and db
    #     uses: dawidd6/action-ansible-playbook@v2
    #     with:
    #       playbook: ${{ github.workspace }}/Ansible/Playbooks/backend.yml
    #       directory: ${{ github.workspace }}/Ansible
    #       vault_password: ${{ secrets.VAULT_PASSWORD }}
    #   inventory: ${{ github.workspace }}/Ansible/aws_ec2.yml
    #   requirements: ${{ github.workspace }}/Ansible/requirements.yml
